### ISSUE TITLE
Cant access CalibreGUI after update 

### ISSUE THREAD

**Issue by Marly212** [linuxserver/docker-calibre#47]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

After I upgraded my Calibre Server Container I can't access the WebUI anymore

------------------------------

## Expected Behavior
I should be able to access the WebUI

## Current Behavior
When I try to access it I am getting the following message:

![grafik](https://user-images.githubusercontent.com/42452096/115353056-5c541200-a1b8-11eb-804f-d25718d83357.png)

## Steps to Reproduce
1. Update Docker Image 
2. Copy the settings from the old Container to the new one
3. Start the Container and try to access it
4.

## Environment
**OS: Synology DS920+
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
From the Docker App on the Synology

## Command used to create docker container (run/create/compose/screenshot)
![grafik](https://user-images.githubusercontent.com/42452096/115353383-b9e85e80-a1b8-11eb-8fa1-c1a492d920d2.png)

## Docker logs
https://pastebin.com/YgNxxbSS

**Comment by j0nnymoe** [comment]
Please provide updated log, pastebin link is invalid.

**Comment by Marly212** [comment]
Sorry Pastebin seems to have a problem with the Data I am trying to Paste, so here are the files I found, hope these are the log files you need
[xorgxrdp.11.log](https://github.com/linuxserver/docker-calibre/files/6341644/xorgxrdp.11.log)
[server-access-log.txt](https://github.com/linuxserver/docker-calibre/files/6341645/server-access-log.txt)
[server-log.txt](https://github.com/linuxserver/docker-calibre/files/6341646/server-log.txt)

**Comment by csharpengineer** [comment]
I am having the same issue, which brought me here.  If you need any additional data points, I'd be happy to provide.

**Comment by csharpengineer** [comment]
The last image that actually works is linuxserver/calibre:v5.14.0-ls107.   Everything after that has the error above.

**Comment by aptalca** [comment]
That error is expected if you're setting a gui password, because the default password the guac client is trying is not accepted. After you hit ok, it should open a prompt window for user/pass, which the user is abc and the password is whatever you set (or `abc` if you're still passing the deprecated GUAC_PASSWORD var)

If you're still having issues, post the command you used to create the container and post your container log to pastebin and drop a link here

**Comment by Marly212** [comment]
Ok so after I press ok on the Screen I can choose where to Install my Libary so it's working, but now I have the problem that every time I restart the Server (for Installing Plugins) Calibre is asking for the Path to install the Library again. So basically Calibre is resetting after a restart

**Comment by aptalca** [comment]
Update your image again and if it doesn't fix it, see #48

**Comment by Marly212** [comment]
OK, Issue #48 seems to fix it, Thanks for the help.

Was there Documentation or some other Notification that I missed to change the HOME environment to /config?

**Comment by aptalca** [comment]
You don't need to change/add anything. We fixed it in the image. But in #48's case, portainer added an unnecessary var for `HOME=/root`, which broke it, but that's just portainer being portainer (hence why we recommend docker-compose)

**Comment by Torqu3Wr3nch** [comment]
> OK, Issue #48 seems to fix it, Thanks for the help.
> 
> Was there Documentation or some other Notification that I missed to change the HOME environment to /config?

It really shouldn't have been necessary for you to do anything. The change was specified in @aptalca's Dockerfile/image. It's a bug caused by Portainer conflating ENV defaults from the image with user-specified ENV values so that all ENV variables going forward after the first image pull are essentially set in stone.

See:
https://github.com/portainer/portainer/issues/4142

https://github.com/portainer/portainer/issues/2952

Any chance you could maybe try to throw your/Linuxserver.io's weight around with the folks at Portainer, @aptalca?

**Comment by aptalca** [comment]
> Any chance you could maybe try to throw your/Linuxserver.io's weight around with the folks at Portainer, @aptalca?

yyeahhhh about that. I'll just leave it at "we used to collaborate with them and provided them with a custom json feed that added most of the linuxserver images as templates into portainer. But one day they just removed it with no heads up or anything"
https://github.com/portainer/portainer/issues/666#issuecomment-414077629

**Comment by Roxedus** [comment]
Just more reasons to switch to yacht

**Comment by aptalca** [comment]
To clarify, what I mentioned above **_is not_** the reason we don't recommend portainer. There is no bad blood or anything. I just can't bother to contribute to portainer after the previous interaction because I feel it would be a waste of my time.

The reason we don't recommend portainer is because they don't do certain things the right way and it ends up being confusing and difficult to troubleshoot. For instance they used libcompose, a long deprecated project, as a compose alternative but pushed it to their users in the gui as if it was docker compose. It wasn't. It didn't work right. And we still get tons of support requests from users claiming they're using compose and it's not working, only to realize later that they're using portainer's compose and not docker compose. I guess now they switched using actual compose on x86_64, but not sure.

Anyway, they continually say that they are going after the enterprise market, so I can't recommend it to homelab users.

[Yacht](https://github.com/SelfhostedPro/Yacht) on the other hand is a project to watch.

**Comment by Torqu3Wr3nch** [comment]
@Roxedus and @aptalca Just to close the loop here, in case others come across it:

> Just more reasons to switch to yacht

yacht has the same problem as Portainer...exactly the same behavior and treatment of the ENV variables.

**Comment by Marly212** [comment]
> 
> 
> You don't need to change/add anything. We fixed it in the image. But in #48's case, portainer added an unnecessary var for `HOME=/root`, which broke it, but that's just portainer being portainer (hence why we recommend docker-compose)

For me, I needed to change the HOME Variable to /config in order for it to work, if I don't change it Calibre is always getting resetted at the start of it.

**Comment by Tiemichael** [comment]
Still having the same issue with V5.16.1 (is it the latest?). Calibre needs to be reconfigured after reboot.
How do I set Home? which file?
Thanks

**Comment by aptalca** [comment]
open a new issue and fill out the issue template
